import streamlit as st
st.title(":blue[Movie Genre Classification]")
st.header("Movies with their genre and Ratings")
st.caption("Created By Chalumuri Harshitha")
#st.caption("From Telangana")
btn_click=st.button("Click me to get the genre of films ")
##st.write(btn_click)
if btn_click==True:
    st.subheader("You clicked me :wave:")
    st.text("Action Film")
    st.text("Animated Film")
    st.text("Horror Film")
    st.text("Romantic Comedy")
    st.text("Thriller")
    st.text("Adventure Film")
    st.text("Comey")
    st.text("Historical drama")
    st.text("Disaster film")
    st.text("Musical")
    st.text("War film")
    st.snow()
